### ISSUE TITLE
Cannot start instance

### ISSUE THREAD

**Issue by mrhoga** [ioBroker/ioBroker.hm-rpc#135]
# hm-rpc instance cannot be started due to script error
Two instances of the adapter are configured, one for HM and another one for HM-IP. While the HM-IP instance is running without problems, the one configured for HM recently stopped working and logs the below messages:

Quelle | Zeit | debug | Meldung
-- | -- | -- | --
host.ioBroker-Pi | 2019-01-04 04:13:37.475 | info | Restart adapter system.adapter.hm-rpc.0 because enabled
host.ioBroker-Pi | 2019-01-04 04:13:37.475 | error | instance system.adapter.hm-rpc.0 terminated with code 0 (OK)
host.ioBroker-Pi | 2019-01-04 04:13:37.475 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/client.js:6:14)
host.ioBroker-Pi | 2019-01-04 04:13:37.475 | error | Caught by controller[0]: at require (internal/module.js:20:19)
host.ioBroker-Pi | 2019-01-04 04:13:37.475 | error | Caught by controller[0]: at Module.require (module.js:497:17)
host.ioBroker-Pi | 2019-01-04 04:13:37.473 | error | Caught by controller[0]: at Function.Module._load (module.js:438:3)
host.ioBroker-Pi | 2019-01-04 04:13:37.472 | error | Caught by controller[0]: at tryModuleLoad (module.js:446:12)
host.ioBroker-Pi | 2019-01-04 04:13:37.470 | error | Caught by controller[0]: at Module.load (module.js:487:32)
host.ioBroker-Pi | 2019-01-04 04:13:37.469 | error | Caught by controller[0]: at Object.Module._extensions..js (module.js:579:10)
host.ioBroker-Pi | 2019-01-04 04:13:37.467 | error | Caught by controller[0]: at Module._compile (module.js:542:28)
host.ioBroker-Pi | 2019-01-04 04:13:37.466 | error | Caught by controller[0]: at Object.runInThisContext (vm.js:97:10)
host.ioBroker-Pi | 2019-01-04 04:13:37.465 | error | Caught by controller[0]: at createScript (vm.js:56:10)
host.ioBroker-Pi | 2019-01-04 04:13:37.463 | error | Caught by controller[0]: SyntaxError: Unexpected token *
host.ioBroker-Pi | 2019-01-04 04:13:37.462 | error | Caught by controller[0]: ^
host.ioBroker-Pi | 2019-01-04 04:13:37.460 | error | Caught by controller[0]: var man = Math.floor((d * (2 ** -exp)) * (1 << 30));
host.ioBroker-Pi | 2019-01-04 04:13:37.460 | error | Caught by controller[0]: /opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:213
host.ioBroker-Pi | 2019-01-04 04:13:35.549 | info | instance system.adapter.hm-rpc.0 started with pid 24276

**Comment by foxriver76** [comment]
The binrpc has received two new versions in the last 24 hours, maybe the version published about 15 hours ago included a syntax error. I would assume that this is fixed with version 3.3.1, published this morning.

**Comment by mrhoga** [comment]
Confirmed, I just reinstalled hm-rpc v. 1.8.2 and the adapter starts without any errors again.
Thank you!

**Comment by Apollon77** [comment]
@foxriver76 but please ^3.3.1!! Not >=
