### ISSUE TITLE
Cannot update Adapter

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.hm-rpc#154]
1.96 -> 1.97 not working.

`$ ./iobroker upgrade hm-rpc
undefined server errorundefined Error: server error
    at Socket.onPacket (/opt/iobroker/node_modules/engine.io-client/lib/socket.js:445:19)
    at XHR.<anonymous> (/opt/iobroker/node_modules/engine.io-client/lib/socket.js:268:10)
    at XHR.Emitter.emit (/opt/iobroker/node_modules/component-emitter/index.js:133:20)
    at XHR.Transport.onPacket (/opt/iobroker/node_modules/engine.io-client/lib/transport.js:145:8)
    at callback (/opt/iobroker/node_modules/engine.io-client/lib/transports/polling.js:144:10)
    at Object.exports.decodePayload (/opt/iobroker/node_modules/engine.io-parser/lib/index.js:309:18)
    at XHR.Polling.onData (/opt/iobroker/node_modules/engine.io-client/lib/transports/polling.js:148:10)
    at Request.<anonymous> (/opt/iobroker/node_modules/engine.io-client/lib/transports/polling-xhr.js:126:10)
    at Request.Emitter.emit (/opt/iobroker/node_modules/component-emitter/index.js:133:20)
    at Request.onData (/opt/iobroker/node_modules/engine.io-client/lib/transports/polling-xhr.js:296:8)`

**Comment by daniel-lo** [comment]
was problem on my side .. sorry
