### ISSUE TITLE
Exchecption bei Refresh der Geräte

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.hm-rpc#21]
2016-03-10 23:25:56.509  - error: uncaught exception: Cannot set property 'hm-rpc.0.BidCoS-RF.1.LEVEL' of null
2016-03-10 23:25:56.588  - error: TypeError: Cannot set property 'hm-rpc.0.BidCoS-RF.1.LEVEL' of null
    at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.hm-rega/hm-rega.js:889:55)
    at Socket.onack (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:305:9)
    at Socket.onpacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:229:12)
    at Manager.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/component-bind/index.js:21:15)
    at Manager.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/component-emitter/index.js:131:20)
    at Manager.ondecoded (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:333:8)
    at Decoder.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/component-bind/index.js:21:15)
    at Decoder.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/socket.io-parser/index.js:247:12)
    at Manager.ondata (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:323:16)
2016-03-10 23:25:57.019  - error: host.cubietruck instance system.adapter.hm-rega.0 terminated with code 6 (uncaught exception)

... an sich hab ich da nichts besonderes. In der CCU finde ich nichts mit einem LEVEL bei dem "Standarddatenpunkt" (ist ja die Zentrale selbst). Im parallel laufeden CCU.io wird als LEVEL der Wert "0" angezeigt

**Comment by GermanBluefox** [comment]
Welche Version?

**Comment by Apollon77** [comment]
CCU: 2.15.5
iobroker: alles aktuell

**Comment by GermanBluefox** [comment]
Da passt was nicht. Du schreibst Fehler gegen hm-rpc obwohl abgestürtzt ist hm-rega.
Also du hast hm-rega 0.2.1 ? oder 0.3.4

**Comment by Apollon77** [comment]
Hi,

ich gehe auf hm-rpc und drücke dort "sync objects (once) und speichere. Dann läuft er los. Und in diesem Prozess kommt dann dieser Fehler

hm-rega ist 0.3.2 ... habe gerade gesehen das es inzwischen die 0.3.5 gibt. Teste es heute Abend

**Comment by Apollon77** [comment]
Aaalso Uodate hm-rega zur 0.3.5 heute war ok ... ausser zwei Fehler im Log:

2016-03-13 19:57:58.926  - info: iobroker npm install iobroker.hm-rega --production --prefix "/opt/iobroker" (System call)
2016-03-13 19:58:14.033  - error: hm-rega.0 runScriptFile Error: ENOENT, open '/opt/iobroker/node_modules/iobroker.hm-rega/lib/../regascripts/polling.fn'
2016-03-13 19:58:14.056  - error: hm-rega.0 runScriptFile Error: ENOENT, open '/opt/iobroker/node_modules/iobroker.hm-rega/lib/../regascripts/programs.fn'
2016-03-13 20:00:08.930  - info: iobroker npm install --production --prefix "/opt/iobroker/node_modules/iobroker.hm-rega" (System call)

Danach habe ich hm-rpc.0 mit "sync objects" editiert.

Nachdem sich hm.rpc.0 innerhalb von 5 mins nicht selbst beendet hatte (immer wieder starts mit "Already running" habe ich manuell gekillt.

Dann gabs den Fehler nicht mehr ...

mache damit hier mal zu. Falls Du für den Update-Fehler ein Issue oder Mantis haben willst sag Bescheid
