### ISSUE TITLE
Cuxd Adapter startet neu

### ISSUE THREAD

**Issue by Schmello** [ioBroker/ioBroker.hm-rpc#299]
Mein Cuxd Adapter startet immer wieder neu. Adapter sind auf dem neusten Stand.
Ich kann mit den Fehlern aus dem Log wenig anfangen. 

`
hm-rpc.1 | 2021-01-10 09:38:42.109 | info | (5566) Connected
-- | -- | -- | --
hm-rpc.1 | 2021-01-10 09:38:42.100 | info | (5566) new CUxD devices/channels after filter: 0
hm-rpc.1 | 2021-01-10 09:38:41.836 | info | (5566) binrpc -> listDevices 210
hm-rpc.1 | 2021-01-10 09:38:41.119 | info | (5566) binrpc client is trying to connect to 192.168.10.3:8701/ with ["xmlrpc_bin://192.168.10.10:8701","IObroker:hm-rpc.1"]
hm-rpc.1 | 2021-01-10 09:38:41.116 | info | (5566) binrpc server is trying to listen on 192.168.10.10:8701
hm-rpc.1 | 2021-01-10 09:38:40.787 | info | (5566) starting. Version 1.14.27 in /opt/iobroker/node_modules/iobroker.hm-rpc, node: v12.20.0, js-controller: 3.1.6
host.IObroker | 2021-01-10 09:38:38.078 | info | instance system.adapter.hm-rpc.1 started with pid 5566
host.IObroker | 2021-01-10 09:38:08.033 | info | Restart adapter system.adapter.hm-rpc.1 because enabled
host.IObroker | 2021-01-10 09:38:08.033 | error | instance system.adapter.hm-rpc.1 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.IObroker | 2021-01-10 09:38:08.032 | error | Caught by controller[0]: at Socket.<anonymous> (/opt/iobroker/node_modules/binrpc/lib/server.js:59:22)
host.IObroker | 2021-01-10 09:38:08.032 | error | Caught by controller[0]: at Server.handleCall (/opt/iobroker/node_modules/binrpc/lib/server.js:82:24)
host.IObroker | 2021-01-10 09:38:08.031 | error | Caught by controller[0]: at Server.EventEmitter.emit (domain.js:483:12)
host.IObroker | 2021-01-10 09:38:08.031 | error | Caught by controller[0]: at Server.emit (events.js:314:20)
host.IObroker | 2021-01-10 09:38:08.030 | error | Caught by controller[0]: at Server.<anonymous> (/opt/iobroker/node_modules/iobroker.hm-rpc/main.js:924:9)
host.IObroker | 2021-01-10 09:38:08.030 | error | Caught by controller[0]: at /opt/iobroker/node_modules/binrpc/lib/server.js:83:41
host.IObroker | 2021-01-10 09:38:08.030 | error | Caught by controller[0]: at Object.encodeResponse (/opt/iobroker/node_modules/binrpc/lib/protocol.js:52:25)
host.IObroker | 2021-01-10 09:38:08.029 | error | Caught by controller[0]: at Object.encodeData (/opt/iobroker/node_modules/binrpc/lib/protocol.js:90:32)
host.IObroker | 2021-01-10 09:38:08.029 | error | Caught by controller[0]: at Object.encodeArray (/opt/iobroker/node_modules/binrpc/lib/protocol.js:156:44)
host.IObroker | 2021-01-10 09:38:08.029 | error | Caught by controller[0]: at Object.encodeData (/opt/iobroker/node_modules/binrpc/lib/protocol.js:69:19)
host.IObroker | 2021-01-10 09:38:08.027 | error | Caught by controller[0]: TypeError: argument 'obj' must be type number, string, boolean or object
hm-rpc.1 | 2021-01-10 09:38:07.781 | info | (5462) Terminated (NO_ERROR): Without reason
hm-rpc.1 | 2021-01-10 09:38:07.779 | info | (5462) terminating
hm-rpc.1 | 2021-01-10 09:38:07.694 | info | (5462) Disconnected
hm-rpc.1 | 2021-01-10 09:38:07.676 | info | (5462) binrpc -> 192.168.10.3:8701/ init ["xmlrpc_bin://192.168.10.10:8701",""]
hm-rpc.1 | 2021-01-10 09:38:07.675 | error | at Socket.<anonymous> (/opt/iobroker/node_modules/binrpc/lib/server.js:59:22)
hm-rpc.1 | 2021-01-10 09:38:07.675 | error | at Server.handleCall (/opt/iobroker/node_modules/binrpc/lib/server.js:82:24)
hm-rpc.1 | 2021-01-10 09:38:07.675 | error | at Server.EventEmitter.emit (domain.js:483:12)
hm-rpc.1 | 2021-01-10 09:38:07.675 | error | at Server.emit (events.js:314:20)
hm-rpc.1 | 2021-01-10 09:38:07.675 | error | at Server.<anonymous> (/opt/iobroker/node_modules/iobroker.hm-rpc/main.js:924:9)
hm-rpc.1 | 2021-01-10 09:38:07.675 | error | at /opt/iobroker/node_modules/binrpc/lib/server.js:83:41
hm-rpc.1 | 2021-01-10 09:38:07.675 | error | at Object.encodeResponse (/opt/iobroker/node_modules/binrpc/lib/protocol.js:52:25)
hm-rpc.1 | 2021-01-10 09:38:07.675 | error | at Object.encodeData (/opt/iobroker/node_modules/binrpc/lib/protocol.js:90:32)
hm-rpc.1 | 2021-01-10 09:38:07.675 | error | at Object.encodeArray (/opt/iobroker/node_modules/binrpc/lib/protocol.js:156:44)
hm-rpc.1 | 2021-01-10 09:38:07.675 | error | at Object.encodeData (/opt/iobroker/node_modules/binrpc/lib/protocol.js:69:19)
hm-rpc.1 | 2021-01-10 09:38:07.675 | error | (5462) TypeError: argument 'obj' must be type number, string, boolean or object
hm-rpc.1 | 2021-01-10 09:38:07.674 | error | (5462) uncaught exception: argument 'obj' must be type number, string, boolean or object
hm-rpc.1 | 2021-01-10 09:36:37.626 | info | (5462) Connected
hm-rpc.1 | 2021-01-10 09:36:37.624 | info | (5462) new CUxD devices/channels after filter: 0
hm-rpc.1 | 2021-01-10 09:36:37.465 | info | (5462) binrpc -> listDevices 210
hm-rpc.1 | 2021-01-10 09:36:36.617 | info | (5462) binrpc client is trying to connect to 192.168.10.3:8701/ with ["xmlrpc_bin://192.168.10.10:8701","IObroker:hm-rpc.1"]
hm-rpc.1 | 2021-01-10 09:36:36.616 | info | (5462) binrpc server is trying to listen on 192.168.10.10:8701
hm-rpc.1 | 2021-01-10 09:36:36.211 | info | (5462) starting. Version 1.14.27 in /opt/iobroker/node_modules/iobroker.hm-rpc, node: v12.20.0, js-controller: 3.1.6
host.IObroker | 2021-01-10 09:36:33.666 | info | instance system.adapter.hm-rpc.1 started with pid 5462
`

**Comment by foxriver76** [comment]
Leider fehlen die Infos aus dem issue template

**Comment by Schmello** [comment]
Woher bekomme ich die infos die du brauchst?

**Comment by foxriver76** [comment]
Admin Tab adapter, dann bei hm-rpc installierte Version, das wäre in dem Fall das wichtige

**Comment by wendy2702** [comment]
Hi,

ich habe das auch mit RPC 1.14.27 nach dem Upgrade. 
JS-Controller 3.1.6
NODE 12.19.0

Was musst du sonst noch wissen?

```
2021-01-10 13:25:31.476  - [32minfo[39m: host.iobroker instance system.adapter.hm-rpc.1 started with pid 23406
2021-01-10 13:25:32.249  - [32minfo[39m: hm-rpc.1 (23406) starting. Version 1.14.27 in /opt/iobroker/node_modules/iobroker.hm-rpc, node: v12.19.0, js-controller: 3.1.6
2021-01-10 13:25:32.330  - [32minfo[39m: hm-rpc.1 (23406) binrpc server is trying to listen on 192.168.178.18:8701
2021-01-10 13:25:32.331  - [32minfo[39m: hm-rpc.1 (23406) binrpc client is trying to connect to 192.168.178.8:8701/ with ["xmlrpc_bin://192.168.178.18:8701","iobroker:hm-rpc.1"]
2021-01-10 13:25:32.376  - [32minfo[39m: hm-rpc.1 (23406) binrpc -> listDevices 18
2021-01-10 13:25:32.417  - [32minfo[39m: hm-rpc.1 (23406) new CUxD devices/channels after filter: 0
2021-01-10 13:25:32.417  - [32minfo[39m: hm-rpc.1 (23406) Connected
2021-01-10 13:27:02.430  - [31merror[39m: hm-rpc.1 (23406) uncaught exception: argument 'obj' must be type number, string, boolean or object
2021-01-10 13:27:02.431  - [31merror[39m: hm-rpc.1 (23406) TypeError: argument 'obj' must be type number, string, boolean or object
    at Object.encodeData (/opt/iobroker/node_modules/binrpc/lib/protocol.js:69:19)
    at Object.encodeArray (/opt/iobroker/node_modules/binrpc/lib/protocol.js:156:44)
    at Object.encodeData (/opt/iobroker/node_modules/binrpc/lib/protocol.js:90:32)
    at Object.encodeResponse (/opt/iobroker/node_modules/binrpc/lib/protocol.js:52:25)
    at /opt/iobroker/node_modules/binrpc/lib/server.js:83:41
    at Server.<anonymous> (/opt/iobroker/node_modules/iobroker.hm-rpc/main.js:924:9)
    at Server.emit (events.js:314:20)
    at Server.handleCall (/opt/iobroker/node_modules/binrpc/lib/server.js:82:24)
    at Socket.<anonymous> (/opt/iobroker/node_modules/binrpc/lib/server.js:59:22)
    at Socket.emit (events.js:314:20)
2021-01-10 13:27:02.432  - [32minfo[39m: hm-rpc.1 (23406) binrpc -> 192.168.178.8:8701/ init ["xmlrpc_bin://192.168.178.18:8701",""]
2021-01-10 13:27:02.435  - [32minfo[39m: hm-rpc.1 (23406) Disconnected
2021-01-10 13:27:02.441  - [32minfo[39m: hm-rpc.1 (23406) terminating
2021-01-10 13:27:02.442  - [32minfo[39m: hm-rpc.1 (23406) Terminated (NO_ERROR): Without reason
2021-01-10 13:27:02.964  - [32minfo[39m: host.iobroker instance system.adapter.hm-rpc.1 terminated with code 0 (NO_ERROR)
2021-01-10 13:27:02.966  - [32minfo[39m: host.iobroker Restart adapter system.adapter.hm-rpc.1 because enabled
2021-01-10 13:27:32.995  - [32minfo[39m: host.iobroker instance system.adapter.hm-rpc.1 started with pid 23562
2021-01-10 13:27:33.833  - [32minfo[39m: hm-rpc.1 (23562) starting. Version 1.14.27 in /opt/iobroker/node_modules/iobroker.hm-rpc, node: v12.19.0, js-controller: 3.1.6
`

**Comment by foxriver76** [comment]
ja .27 hat cuxd kaputt gemacht, daher bitte entweder die aktuelle latest nutzen oder stable ;-)

**Comment by wendy2702** [comment]
Im latest wird einem die 1.14.27 als aktuellstes angeboten:

![grafik](https://user-images.githubusercontent.com/33424168/104123230-2f3acc80-534a-11eb-9e04-6267fbaff256.png)
