### ISSUE TITLE
Is Homegear supported only in XML mode?

### ISSUE THREAD

**Issue by qm3ster** [ioBroker/ioBroker.hm-rpc#57]
I installed a default install of `ioBroker` and `homegear` on a fresh Ubuntu 16.04 install.
XML mode works, but switching to BIN-RPC causes the following:
```

2018-02-03 23:45:20.068 - info: host.ip-172-31-3-34 instance system.adapter.hm-rpc.0 started with pid 24397
--
2018-02-03 23:45:20.396 - info: hm-rpc.0 starting. Version 1.5.1 in /opt/iobroker/node_modules/iobroker.hm-rpc, node: v8.9.4
2018-02-03 23:45:20.736 - info: hm-rpc.0 binrpc server is trying to listen on 127.0.0.1:2004
2018-02-03 23:45:20.736 - info: hm-rpc.0 binrpc client is trying to connect to 127.0.0.1:2001 with ["xmlrpc_bin://127.0.0.1:2004","hm-rpc.0"]
2018-02-03 23:45:20.945 - info: hm-rpc.0 Connected
2018-02-03 23:45:21.444 - error: hm-rpc.0 uncaught exception: Cannot read property 'toString' of null
2018-02-03 23:45:21.445 - error: hm-rpc.0 TypeError: Cannot read property 'toString' of null
at Object.decodeData (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:371:82)
at rec (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:432:32)
at Object.decodeStrangeRequest (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:441:9)
at Object.decodeRequest (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:476:32)
at Socket. (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/server.js:50:38)
at emitOne (events.js:116:13)
at Socket.emit (events.js:211:7)
at addChunk (_stream_readable.js:263:12)
at readableAddChunk (_stream_readable.js:250:11)
at Socket.Readable.push (_stream_readable.js:208:10)
2018-02-03 23:45:21.445 - info: hm-rpc.0 binrpc -> 127.0.0.1:2001 init ["xmlrpc_bin://127.0.0.1:2004",""]
2018-02-03 23:45:22.446 - info: hm-rpc.0 binrpc -> 127.0.0.1:2001 init ["xmlrpc_bin://127.0.0.1:2004",""]
2018-02-03 23:45:22.450 - error: Caught by controller[0]: TypeError: Cannot read property 'toString' of null
2018-02-03 23:45:22.451 - error: Caught by controller[0]: at Object.decodeData (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:371:82)
2018-02-03 23:45:22.451 - error: Caught by controller[0]: at rec (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:432:32)
2018-02-03 23:45:22.451 - error: Caught by controller[0]: at Object.decodeStrangeRequest (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:441:9)
2018-02-03 23:45:22.451 - error: Caught by controller[0]: at Object.decodeRequest (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:476:32)
2018-02-03 23:45:22.451 - error: Caught by controller[0]: at Socket. (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/server.js:50:38)
2018-02-03 23:45:22.451 - error: Caught by controller[0]: at emitOne (events.js:116:13)
2018-02-03 23:45:22.451 - error: Caught by controller[0]: at Socket.emit (events.js:211:7)
2018-02-03 23:45:22.451 - error: Caught by controller[0]: at addChunk (_stream_readable.js:263:12)
2018-02-03 23:45:22.451 - error: Caught by controller[0]: at readableAddChunk (_stream_readable.js:250:11)
2018-02-03 23:45:22.451 - error: Caught by controller[0]: at Socket.Readable.push (_stream_readable.js:208:10)
2018-02-03 23:45:22.451 - error: host.ip-172-31-3-34 instance system.adapter.hm-rpc.0 terminated with code 6 (uncaught exception)
2018-02-03 23:45:22.451 - info: host.ip-172-31-3-34 Restart adapter system.adapter.hm-rpc.0 because enabled
```

**Comment by Apollon77** [comment]
Please try to start hm-rpc.0 in Debug mode (instances - expertmode -loglevel to Debug. And post log then again. Thank you

**Comment by qm3ster** [comment]
@Apollon77 I have a problem with authority so I set `silly` instead.
```
2018-02-07 23:19:32.310 - info: host.ip-172-31-3-34 instance system.adapter.hm-rpc.0 started with pid 19754
--
2018-02-07 23:19:32.521 - debug: hm-rpc.0 objectDB connected
2018-02-07 23:19:32.534 - debug: hm-rpc.0 statesDB connected
2018-02-07 23:19:32.625 - info: hm-rpc.0 starting. Version 1.5.1 in /opt/iobroker/node_modules/iobroker.hm-rpc, node: v8.9.4
2018-02-07 23:19:32.648 - silly: hm-rpc.0 inMem message hm-rpc.0.* hm-rpc.0.info.connection val=false, ack=true, ts=1518045572647, q=0, from=system.adapter.hm-rpc.0, lc=1518045572647
2018-02-07 23:19:32.961 - info: hm-rpc.0 binrpc server is trying to listen on 127.0.0.1:2004
2018-02-07 23:19:32.962 - info: hm-rpc.0 binrpc client is trying to connect to 127.0.0.1:2001 with ["xmlrpc_bin://127.0.0.1:2004","hm-rpc.0"]
2018-02-07 23:19:32.962 - debug: hm-rpc.0 Connect...
2018-02-07 23:19:33.164 - debug: hm-rpc.0 binrpc -> 127.0.0.1:2001 init ["xmlrpc_bin://127.0.0.1:2004","hm-rpc.0"]
2018-02-07 23:19:33.170 - info: hm-rpc.0 Connected
2018-02-07 23:19:33.171 - debug: hm-rpc.0 start ping interval
2018-02-07 23:19:33.172 - silly: hm-rpc.0 inMem message hm-rpc.0.* hm-rpc.0.info.connection val=true, ack=true, ts=1518045573171, q=0, from=system.adapter.hm-rpc.0, lc=1518045573171
2018-02-07 23:19:33.670 - error: hm-rpc.0 uncaught exception: Cannot read property 'toString' of null
2018-02-07 23:19:33.670 - error: hm-rpc.0 TypeError: Cannot read property 'toString' of null
at Object.decodeData (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:371:82)
at rec (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:432:32)
at Object.decodeStrangeRequest (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:441:9)
at Object.decodeRequest (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:476:32)
at Socket. (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/server.js:50:38)
at emitOne (events.js:116:13)
at Socket.emit (events.js:211:7)
at addChunk (_stream_readable.js:263:12)
at readableAddChunk (_stream_readable.js:250:11)
at Socket.Readable.push (_stream_readable.js:208:10)
2018-02-07 23:19:33.670 - info: hm-rpc.0 binrpc -> 127.0.0.1:2001 init ["xmlrpc_bin://127.0.0.1:2004",""]
2018-02-07 23:19:34.672 - info: hm-rpc.0 binrpc -> 127.0.0.1:2001 init ["xmlrpc_bin://127.0.0.1:2004",""]
2018-02-07 23:19:34.675 - error: Caught by controller[0]: TypeError: Cannot read property 'toString' of null
2018-02-07 23:19:34.676 - error: Caught by controller[0]: at Object.decodeData (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:371:82)
2018-02-07 23:19:34.676 - error: Caught by controller[0]: at rec (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:432:32)
2018-02-07 23:19:34.676 - error: Caught by controller[0]: at Object.decodeStrangeRequest (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:441:9)
2018-02-07 23:19:34.676 - error: Caught by controller[0]: at Object.decodeRequest (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/protocol.js:476:32)
2018-02-07 23:19:34.676 - error: Caught by controller[0]: at Socket. (/opt/iobroker/node_modules/iobroker.hm-rpc/node_modules/binrpc/lib/server.js:50:38)
2018-02-07 23:19:34.676 - error: Caught by controller[0]: at emitOne (events.js:116:13)
2018-02-07 23:19:34.676 - error: Caught by controller[0]: at Socket.emit (events.js:211:7)
2018-02-07 23:19:34.676 - error: Caught by controller[0]: at addChunk (_stream_readable.js:263:12)
2018-02-07 23:19:34.676 - error: Caught by controller[0]: at readableAddChunk (_stream_readable.js:250:11)
2018-02-07 23:19:34.676 - error: Caught by controller[0]: at Socket.Readable.push (_stream_readable.js:208:10)
2018-02-07 23:19:34.676 - error: host.ip-172-31-3-34 instance system.adapter.hm-rpc.0 terminated with code 6 (uncaught exception)
2018-02-07 23:19:34.676 - info: host.ip-172-31-3-34 Restart adapter system.adapter.hm-rpc.0 because enabled
```

**Comment by GermanBluefox** [comment]
Does homegear support bin?

**Comment by qm3ster** [comment]
@GermanBluefox https://doc.homegear.eu/data/homegear/communication_protocols.html#binary-rpc (even mentions ioBroker)
The last line here also suggest it's enabled by default: https://doc.homegear.eu/data/homegear/first_steps.html

**Comment by qm3ster** [comment]
Seems like it's always enabled if XML is.
https://github.com/Homegear/Homegear/blob/cdfda3209b4a95b91f0a5d3a7ef23b2601ff8a52/misc/Config%20Directory/rpcservers.conf#L10-L12

**Comment by GermanBluefox** [comment]
If you reinstall the driver, do still have the error? Because there was the update for binrpc and it will be taken by new installations. 
Check the version of installed binrpc package. It must be 3.1.2

**Comment by GermanBluefox** [comment]
Closed because no reaction
