### ISSUE TITLE
Adapter Fehler nach Update auf 1.15.7

### ISSUE THREAD

**Issue by dwm66** [ioBroker/ioBroker.hm-rpc#902]
Nach Update auf 1.15.17 kommt vom Adapter folgender Fehler:

`Error: Cannot find module 'timers/promises'
Require stack:
- /opt/iobroker/node_modules/iobroker.hm-rpc/build/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.hm-rpc/build/main.js:31:20)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/opt/iobroker/node_modules/iobroker.hm-rpc/build/main.js' ]
}`

Downgrade auf 1.15.16 macht's wieder heile.

**Versions:**
 - hm-rpc version: 1.15.17
 - hm-rega version: 3.0.46
 - JS-Controller version: 4.0.24
 - Node version: 14.19.0
 - Operating system: debian linux / buanet docker container release 6.1.0
 - CCU model: CCU2
 - CCU firmware: 2.61.7

**Comment by foxriver76** [comment]
Die neue Versuion benötigt Node 16 hatte ich nicht auf dem Schirm.
